name: 'Install Deployer'
description: 'Installs the `depl` Rust crate from crates.io'
author: 'Klimenty Titov <aclo.create@gmail.com>'

runs:
  using: 'composite'
  steps:
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: 'impulse-sw/deployer'
        regex: true
        file: "deployer-.*\\.deb"
        target: 'depl.deb'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install `depl`
      shell: bash
      run: |
        sudo dpkg -i ./depl.deb
        rm depl.deb

branding:
  icon: 'check-circle'
  color: 'blue'
